### ISSUE TITLE
Still supported?

### ISSUE THREAD

**Issue by Twix53791** [MuratovAS/micro-fzfinder#1]
Hello @MuratovAS,

Thank you for sharing this plugin, a better implementation of the "official" plugin on micro-plugin-channel. I discovered Micro a couple of days ago and I am switching to it. I am a huge fan of fzf (I use it for everything on my computer!), and I would like to contribute to your repo to implement some more advanced features. You still manage the repo?

Some ideas I ve got:
- adding a setting/a flag (both?) to set if we open files: main window/new tab/split
- if its possible, setting to enable a 'popup window' (just run fzf in a new terminal spawming in the background), just for the beauty of a floating window a bit like in Helix.
- possibility to create files (just add --print query : if query & not matches, create a new file)
- possibility to pass the FZF DEFAULT COMMAND as like as the options, for example to use the beautifull colored output of fd instead of  just fzf

I am gonna probably quickly work on that as I am setting up my Micro set-up, and I will do pull request on each feature in your repo and I will be waiting to hear from you.

Regards
Twix

**Comment by MuratovAS** [comment]
yes, I manage the repository.
I'll gladly accept your changes if they work.

**Comment by MuratovAS** [comment]
Idea:
I'd like to open fzf not from the micro launch directory, but from the directory of the open file.

Example:
I execute the command
```
~$ micro /etc/ssh/sshd_config 
```
When I open `fzf`, I see the contents of the `~` directory. But i would like to see the files in the directory `/etc/ssh/`

**Comment by Twix53791** [comment]
Hi Muratov, great ! I have done a couple of things yet :)

I found a way to implement your idea by the way !

PS: about my last idea of opening fzf in a popup window, I think finally it is a bad idea. A lot a complicate things for few benefits. Probably with the builtin micro function `RunTermEmulator` we can run fzf in a splitter buffer, but we loose the beautiful colors of fd and it seems slower. And if we run an external terminal, the problem is to communicate with it, we need an external script... Well I think it is good like that, simple but very efficient I think!
