### ISSUE TITLE
Plugin reports incorrect version

### ISSUE THREAD

**Issue by dev-nicolaos** [MuratovAS/micro-fzfinder#10]
**Environment**

- OS: Fedora 40
- Micro version: 2.0.14
- `pluginrepos` set to `["https://raw.githubusercontent.com/MuratovAS/micro-fzfinder/main/repo.json"]`

When running `plugin list` in micro with this plugin installed the output incorrectly lists this plugin's version as 0.1.0.

```log
> plugin list
The following plugins are currently installed:
...
fzfinder (0.1.0)
...
```

Not 100% sure, but this may be due to [the `VERSION` variable being set in fzfinder.lua](https://github.com/MuratovAS/micro-fzfinder/blob/main/fzfinder.lua#L1). I would have expected Micro to use [the version specified in repo.json](https://github.com/MuratovAS/micro-fzfinder/blob/main/repo.json#L8), but if it does that'd probably be an upstream issue in Micro itself.

**Comment by MuratovAS** [comment]
Thank you. The problem has been fixed.
